config/routes.rb
Devotetest::Application.routes.draw do

  root :to => 'projects#index'

  resources :projects do

    member do
      put :update_test_suite
    end

    resource :test_suite

    resources :tests do
      resources :comments
    end

  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :commentable, :polymorphic => true

end

# == Schema Information
#
# Table name: comments
#
#  id              :integer         not null, primary key
#  comentable_id   :integer
#  comentable_type :string(255)
#  comment         :text
#  created_at      :datetime
#  updated_at      :datetime
#

app/models/project.rb
class Project < ActiveRecord::Base
  validates :name, :git_repository, :presence => true
  has_many :test_suites
  has_many :tests, :class_name => "TestDefinition"

  def initialize_repo
    unless new_record? || project_retrieved?
      Devotest::ProjectRetriever.initialize_repo(self)
    end
  end

  def rebuild_current_test_suite
    initialize_repo unless project_retrieved?
    
    return current_test_suite if latest_version_parsed?

    tests = project_retriever.retrieve_tests
    if tests
      tests.map! {|test| TestDefinition.build_from_info(test) }
      test_suites.create :tests => tests, :revision => latest_revision
    end

  end

  def current_test_suite
    test_suites.first
  end

  def local_repo_path
    return '' unless persisted?
    Rails.root + "tmp" + to_param
  end

  def project_retrieved?
    persisted? && local_repo_path.exist?
  end

  def latest_version_parsed?
    current_test_suite? && 
    current_test_suite.revision == project_retriever.latest_test_suite_revision
  end

  def current_test_suite?
    !current_test_suite.nil?
  end

private

  def latest_revision
    project_retriever.latest_test_suite_revision
  end

  def project_retriever
    @project_retriever ||= Devotest::ProjectRetriever.new(self)
  end

end

# == Schema Information
#
# Table name: projects
#
#  id             :integer         not null, primary key
#  name           :string(255)
#  git_repository :string(255)
#  created_at     :datetime
#  updated_at     :datetime
#

app/models/test_definition.rb
class TestDefinition < ActiveRecord::Base

  has_and_belongs_to_many :test_suites
  has_many :comments, :as => :commentable
  belongs_to :previous_test_version, :class_name => "TestDefinition"
  belongs_to :project

  delegate :sexp, :to_code, :to => :snippet
  serialize :snippet, TestParser::Snippet

  def self.build_from_info(test)
    new(
      :snippet           => test.snippet,
      :identification    => test.identification,
      :testing_framework => test.type
    )
  end

end


# == Schema Information
#
# Table name: test_definitions
#
#  id                       :integer         not null, primary key
#  test_suite_id            :integer
#  previous_test_version_id :integer
#  identification           :string(255)
#  snippet                  :text
#  testing_framework        :string(255)
#  created_at               :datetime
#  updated_at               :datetime
#

app/models/test_suite.rb
class TestSuite < ActiveRecord::Base

  default_scope order('created_at DESC')
  has_and_belongs_to_many :tests, :class_name => "TestDefinition", :after_add => :assign_project
  
  belongs_to :project

  include Enumerable
  
  def each
    return enum_for(:each) unless block_given?

    tests.each {|test| yield(test) }
  end

private

  def assign_project(test)
    test.project = self.project
  end

end

# == Schema Information
#
# Table name: test_suites
#
#  id         :integer         not null, primary key
#  project_id :integer
#  revision   :string(255)
#  created_at :datetime
#  updated_at :datetime
#

app/models/vote.rb
class Vote < ActiveRecord::Base

  belongs_to :test_definition

end

# == Schema Information
#
# Table name: votes
#
#  id                 :integer         not null, primary key
#  test_definition_id :integer
#  value              :integer
#  created_at         :datetime
#  updated_at         :datetime
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def index
    @comments = end_of_association_chain.comments
    respond_to do |wants|
      wants.js
    end
  end

  def create
    @comment = end_of_association_chain.comments.create(params[:comment])
    respond_to do |wants|
      wants.html { redirect_to :back }
      wants.js do 
        @comments = end_of_association_chain.comments
        render 'index'
      end
    end
  end

private

  def end_of_association_chain
    @project ||= Project.find(params[:project_id])
    @test    ||= TestDefinition.find(params[:test_id])
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.xml
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.xml
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.xml
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.xml
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to(@project, :notice => 'Project was successfully created.') }
        format.xml  { render :xml => @project, :status => :created, :location => @project }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.xml
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to(@project, :notice => 'Project was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.xml
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to(projects_url) }
      format.xml  { head :ok }
    end
  end
  
  def update_test_suite
    @project = Project.find(params[:id])
    @project.rebuild_current_test_suite
    
    respond_to do |format|
      format.html { redirect_to :back }
      format.xml  { head :ok }
    end
  end
end

app/controllers/test_suites_controller.rb
class TestSuitesController < ApplicationController
  
  def show
    @test_suite = end_of_association_chain.current_test_suite
  end
  
private

  def end_of_association_chain
    @project ||= Project.find(params[:project_id])
  end

end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  def show
    @test = TestDefinition.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def present_test_identification(test_definition)
    test_definition.identification
  end
end

app/views/comments/_comments.html.erb
<h4>Comments</h4>
<ol>
  <% comments.each do |comment| %>
    <li><%= comment.comment %></li>
  <% end %>
</ol>

<%= render :partial => 'comments/form', :locals => { 
      :project => project, :test => test 
    } %>

app/views/comments/_form.html.erb
<%= form_for(Comment.new, 
    :url => project_test_comments_path(project, test), :remote => true) do |f| %>
  <div class="field">
    <%= f.label :comment, "Add a new Comment" %><br />
    <%= f.text_area :comment, :size => '80x10' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end%>

app/views/comments/index.js.erb
<% comments_html = render :partial => 'comments', :locals => {:comments => @comments, :test => @test, :project => @project } %>

$("#<%= dom_id(@test) %> .comments").empty().append($("<%= escape_javascript(comments_html) %>"))

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Devotetest</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :git_repository %><br />
    <%= f.text_field :git_repository %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Git repository</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @projects.each do |project| %>
  <tr>
    <td><%= project.name %></td>
    <td><%= project.git_repository %></td>
    <td><%= link_to 'Show', project %></td>
    <td><%= link_to 'Edit', edit_project_path(project) %></td>
    <td><%= link_to 'Destroy', project, :confirm => 'Are you sure?', :method => :delete %></td>
    <td><%= link_to 'Update test suite', update_test_suite_project_path(project), :method => :put %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @project.name %>
</p>

<p>
  <b>Git repository:</b>
  <%= @project.git_repository %>
</p>

<% if @project.current_test_suite? %>
  <p>
    <b>Some of the tests in the <%= link_to "current test suite", project_test_suite_path(@project) %>:</b>
    <ul>
      <%- @project.current_test_suite.take(5).each do |test| %>
        <%= render :partial => 'test_suites/test_item', :locals => 
            { :test => test, :project => @project } %>
      <% end %>
    </ul>
    <%= link_to 'See full test suite', project_test_suite_path(@project) %>
  </p>
<% end %>

<%= link_to 'Update test suite', 
    update_test_suite_project_path(@project), :method => :put %> | 
<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/test_suites/_test_item.html.erb
<%= content_tag_for(:li, test) do %>

  <h4>
    <%= link_to present_test_identification(test), 
                project_test_path(project, test) %>
  </h4>

  <%= raw CodeRay.scan(test.to_code, :ruby).div %>

  <div class='comments'>
    <%= link_to "Check comments", 
        project_test_comments_path(project, test), :remote => true %>
  </div>

<% end %>

app/views/test_suites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @project.name %>
</p>

<p>
  <b>Git repository:</b>
  <%= @project.git_repository %>
</p>

<p>
  <b>Tests:</b>
  <ul>
    <%- @test_suite.each do |test| %>
      <%= render :partial => 'test_item', :locals => {
      :test => test, :project => @project
      } %>
    <% end %>
  </ul>
</p>

<%= link_to 'Update test suite', 
            update_test_suite_project_path(@project), :method => :put %> | 

<%= link_to 'Edit', edit_project_path(@project) %> |

<%= link_to 'Back', projects_path %>